### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by repalash** [faysal-ishtiaq/image-segmentation-keras-py3#1]
Is this repo complete? Doesn't seem to work with python3. 
The code seems like the same as the original one.

**Comment by faysal-ishtiaq** [comment]
Yes, it's almost same. Just enough changes were made to work with python 3. Please paste the error message, so that I could solve it.

**Comment by repalash** [comment]
All the print calls are still same for that of python2. And I was getting some errors on importing Models.

Anyways I was able to use the original one in python2.
